// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://lljkrhoohztghdsbypnw.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImxsamtyaG9vaHp0Z2hkc2J5cG53Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDQyOTY1NDksImV4cCI6MjA1OTg3MjU0OX0.U4YgWNgJL2kbJh0jShdwMF4jTbTicSU0asTO1n2cwSk";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);